name: Build Biocrust App

on:
  push:
    branches:
      - main

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build and Package Electron App (Windows)
        run: npm run electron:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: release/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build and Package Electron App (macOS)
        run: npm run electron:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-Installer
          path: release/*.dmg
